### ISSUE TITLE
dill fails to find libffi

### ISSUE THREAD

**Issue by yurivict** [GTkorvo/dill#43]
libffi-3.4.4 is installed, but dill's configure fails to find it:
```
Using private copy of libffi
```
and then the build fails:
```
===>  Building for dill-2.4.1.73
ninja: error: 'libffi/install/lib/libffi.so', needed by 'lib/libdill.so.3.0.0', missing and no known rule to make it
```

Version: 2.4.1
FreeBSD 14.0

**Comment by eisenhauer** [comment]
Hmm.  It looks like our attempt to usually *not* use libffi (which is necessary only in extraordinary circumstances) went awry.  Would you please test current master (after this mornings PR) and see if it behaves better.  If so, we can pull that upstream into ADIOS2.

**Comment by yurivict** [comment]
It builds now on FreeBSD.

**Comment by eisenhauer** [comment]
Closing as fixed in master.
