### ISSUE TITLE
#40 breaks build on Cray-HPC

### ISSUE THREAD

**Issue by tybulut** [GTkorvo/dill#49]
The breaking PR: https://github.com/GTkorvo/dill/pull/40/files

**System**:
https://gw4-isambard.github.io/docs/user-guide/XCI.html

**Error message**:
./ADIOS2/thirdparty/dill/dill/arm8.c:1520:31: error: unknown type name 'arm8_rt_call_link'
 1520 | extern void arm8_rt_call_link(arm8_rt_call_link(char *code, call_t *t);
      |                               ^~~~~~~~~~~~~~~~~
./ADIOS2/thirdparty/dill/dill/arm8.c:1523:1: error: storage class specified for parameter 'arm8_call_link'
 1523 | arm8_call_link(dill_stream s)
      | ^~~~~~~~~~~~~~
./ADIOS2/thirdparty/dill/dill/arm8.c:1524:1: error: expected ';', ',' or ')' before '{' token
 1524 | {
      | ^
make[2]: *** [thirdparty/dill/dill/CMakeFiles/dill.dir/build.make:217: thirdparty/dill/dill/CMakeFiles/dill.dir/arm8.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3545: thirdparty/dill/dill/CMakeFiles/dill.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by eisenhauer** [comment]
Interesting, but not clear what is going on.  Obviously part of the ADIOS build, and presumably something went wrong in parsing before this line to get an "unknown type name" error, but I don't think we can sort without more info.

**Comment by tybulut** [comment]
Let me know what information you need.  

In the mean time let me include the module names with versions in it. In case it might help:

- modules/3.2.11.4
- system-config/3.6.3070-7.0.2.1_7.3__g40f385a9.ari
- craype-network-aries
- Base-opts/2.4.142-7.0.2.1_2.69__g8f27585.ari
- alps/6.6.59-7.0.2.1_3.62__g872a8d62.ari
- nodestat/2.3.89-7.0.2.1_2.53__g8645157.ari
- craype/2.6.2
- sdb/3.3.812-7.0.2.1_2.74__gd6c4e58.ari
- cray-libsci/20.09.1
- udreg/2.3.2-7.0.2.1_2.24__g8175d3d.ari
- pmi/5.0.17
- ugni/6.0.14.0-7.0.2.1_3.24__ge78e5b0.ari
- atp/3.11.7
- gni-headers/5.0.12.0-7.0.2.1_2.27__g3b1768f.ari
- rca/2.2.20-7.0.2.1_2.76__g8e3fb5b.ari
- dmapp/7.1.1-7.0.2.1_2.75__g38cf134.ari
- perftools-base/21.05.0
- xpmem/2.2.20-7.0.2.1_2.61__g87eb960.ari
- llm/21.4.629-7.0.2.1_2.53__g8cae6ef.ari
- cray-mpich/7.7.17
- gcc/10.3.0
- tools/cmake/3.24.2
- PrgEnv-gnu/6.0.9
- cray-mpich-abi/7.7.17
- cray-hdf5-parallel/1.12.0.4
- cray-fftw/3.3.8.10

**Comment by tybulut** [comment]
This issue seems to be fixed with ADIOS release 2_10.  I will close it.
